name: CI - DevOps Portfolio

on:
  push:
    branches:
      - "develop"
      - "main"
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Validar Docker Compose
        run: |
          docker compose config

      - name: Build da aplicação
        run: |
          docker compose build

      - name: Subir containers
        run: |
          docker compose up -d

      - name: Aguardar inicialização dos serviços (App + DB)
        run: |
          sleep 10

      - name: Verificar status dos containers
        run: |
          docker compose ps

      - name: Testar aplicação com retentativas
        run: |
          curl --fail --retry 5 --retry-delay 3 http://localhost:3000

      - name: Exibir logs em caso de falha
        if: failure()
        run: |
          docker compose logs

      - name: Finalizar ambiente
        if: always()
        run: |
          docker compose down